"""Generate the extension's packaged remote-image allowlist."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from urllib.parse import quote


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("revision")
    args = parser.parse_args()

    if not re.fullmatch(r"[0-9a-f]{40}", args.revision):
        raise ValueError("revision must be a full 40-character Git commit")

    catalog = json.loads(args.manifest.read_text(encoding="utf-8"))
    repository_root = args.manifest.parent.parent.parent.resolve()
    repository_url = (
        "https://raw.githubusercontent.com/tannerface26-dev/uvs-tts-assets/"
        f"{args.revision}/"
    )
    output: dict[str, list[dict[str, str]]] = {}

    def build_image_url(relative_source_path: str) -> str:
        image_path = (args.manifest.parent / relative_source_path).resolve()
        relative_path = image_path.relative_to(repository_root)
        encoded_path = "/".join(quote(part, safe="") for part in relative_path.parts)

        if not image_path.is_file():
            raise FileNotFoundError(image_path)

        return repository_url + encoded_path

    for card in catalog["cards"]:
        original = {
            "label": "Original",
            "setId": card["original"]["setId"],
            "cardNumber": card["original"]["cardNumber"],
        }
        if card.get("transformBackOriginal"):
            original["transformBack"] = {
                "label": "Original Transformed Back",
                "setId": card["transformBackOriginal"]["setId"],
                "cardNumber": card["transformBackOriginal"]["cardNumber"],
            }

        variants = [original]
        for variant in card["variants"]:
            set_id, card_number = variant["qualifier"].split("/", maxsplit=1)

            if set_id != "repo" or not re.fullmatch(r"\d+-\d+", card_number):
                raise ValueError(f"Invalid runtime qualifier: {variant['qualifier']}")

            generated_variant = {
                "label": variant["label"],
                "setId": set_id,
                "cardNumber": card_number,
                "imageUrls": {
                    "full": build_image_url(variant["sourcePath"]),
                    "preview": build_image_url(variant["previewPath"]),
                    "mini": build_image_url(variant["previewPath"]),
                    "micro": build_image_url(variant["microPath"]),
                },
            }
            if variant.get("transformBack"):
                back = variant["transformBack"]
                back_set_id, back_card_number = back["qualifier"].split(
                    "/", maxsplit=1
                )
                generated_variant["transformBack"] = {
                    "label": back["cardName"],
                    "setId": back_set_id,
                    "cardNumber": back_card_number,
                    "imageUrls": {
                        "full": build_image_url(back["sourcePath"]),
                        "preview": build_image_url(back["previewPath"]),
                        "mini": build_image_url(back["previewPath"]),
                        "micro": build_image_url(back["microPath"]),
                    },
                }

            variants.append(generated_variant)

        output[str(card["uvsUltraCardId"])] = variants

    destination = Path(__file__).parent.parent / "remote-card-art.js"
    generated = (
        "// Generated by scripts/build-remote-card-art.py. Do not edit by hand.\n"
        "globalThis.UVSU_REMOTE_CARD_ART = Object.freeze("
        + json.dumps(output, ensure_ascii=True, indent=4)
        + ");\n"
    )
    destination.write_text(generated, encoding="utf-8", newline="\n")
    print(f"cards={len(output)} variants={sum(map(len, output.values()))}")


if __name__ == "__main__":
    main()
